config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'orders/index'
  # get 'contacts/index'
  # get 'abouts/index'
  # get 'abouts/show'
  # get 'products/index'
  # get 'products/show'
  # get 'users/index'
  # get 'users/show'
  get '/users', to: 'users#index'
  get '/users/:id', to: 'users#show', id: /\d+/, as: 'user'
  get '/categories', to: 'categories#index'
  get '/categories/:id', to: 'categories#show', id: /\d+/, as: 'category'
  get '/products', to: 'products#index'
  get '/products/:id', to: 'products#show', id: /\d+/, as: 'product'
  get '/about', to: 'abouts#index'
  get '/contact', to: 'contacts#index'
  get '/searchproduct', to: 'products#search', as: 'searchproduct'
  get '/newproducts', to: 'products#new_products', as: 'newproducts'
  get '/updateproducts', to: 'products#update_products', as: 'updateproducts'
  get '/searchbycategories/:id/', to: 'category#search_by_categories', id: /\d+/, as: 'searchbycategories'

  get '/orders', to: 'orders#index'
  post '/orders/add_to_cart/:id', to: 'orders#add_to_cart', as: 'add_to_cart'
  delete '/orders/remove_from_cart/:id', to: 'orders#remove_from_cart', as: 'remove_from_cart'
  get '/orders', to: 'orders#select_province', as: 'select_province'
  get '/orders/pre_checkout', to: 'orders#pre_checkout', as: 'pre_checkout'
  post '/orders/pre_checkout', to: 'orders#pre_checkout_user', as: 'pre_checkout_user'
  post '/orders/pre_checkout', to: 'orders#pre_checkout_address', as: 'pre_checkout_address'

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success' # 20:54 time youtube video
  end

  root to: 'products#index'
  # get 'categories/index'
  # get 'categories/show'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
end

app/models/address.rb
# frozen_string_literal: true

class Address < ApplicationRecord
  belongs_to :user
  belongs_to :province

  validates :street, :city, :postal_code, presence: true
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :products

  validates :name, presence: true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  belongs_to :user
  has_many :order_products

  validates :status, :pst, :gst, :hst, :total, presence: true
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  belongs_to :user
  belongs_to :category

  has_one_attached :image
  has_many :order_products

  validates :title, :price, :quantity, :description, :image, presence: true
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :addresses
  validates :name, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :products
  has_many :addresses

  validates :username, :email, :first_name, :last_name, presence: true
end

app/controllers/abouts_controller.rb
# frozen_string_literal: true

class AboutsController < ApplicationController
  def index
    @abouts = About.all
  end

  def show; end
end

app/controllers/checkout_controller.rb
# frozen_string_literal: true

class CheckoutController < ApplicationController
  def create
    order = Order.find(session[:s_order])

    if order.nil?
      redirect_to pre_checkout_path
      return
    end
    user = User.find(order.user_id)
    @session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      line_items: [{
        name: user.email,
        amount: order.total.to_i * 100,
        currency: 'cad',
        quantity: 1
      }],
      success_url: checkout_success_url + '?session_id={CHECKOUT_SESSION_ID}',
      cancel_url: checkout_cancel_url
    )

    respond_to do |format|
      format.js
    end
  end

  def success
    @order = Order.find(session[:s_order])
    @session = Stripe::Checkout::Session.retrieve(params[:session_id])
    @payment_intent = Stripe::PaymentIntent.retrieve(@session.payment_intent)
    @order.update(stripe_id: @payment_intent.id, status: 'paid')

    @cart.each do |product|
      OrderProduct.create(order_id: @order.id, product_id: product.id, price: product.price, quantity: 1)
      session[:invoice_product] << product.id
    end

    @invoiceProductList = Product.find(session[:invoice_product])
    @cart = nil
    session.delete :cart
    session.delete :current_user
  end

  def cancel
    redirect_to pre_checkout_path
  end
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  before_action :initialize_session
  before_action :select_province

  def index
    # @province = Province.all
  end

  def pre_checkout_user
    @province = Province.find(session[:s_province])
    new_user ||= User.create(username: params[:email], email: params[:email], first_name: params[:first_name], last_name: params[:last_name])
    new_user.addresses.create(user_id: new_user.id, province_id: @province.id, street: params[:street], city: params[:city], postal_code: params[:postal_code])
    session[:current_user] = new_user.id
    subtotal = session[:s_subtotal]
    pst = @province.pst.to_f / 100 * subtotal.to_f
    gst = @province.gst.to_f / 100 * subtotal.to_f
    hst = @province.hst.to_f / 100 * subtotal.to_f
    total = subtotal + pst + gst + hst
    new_order = Order.create(user_id: new_user.id, status: 'new', pst: pst, gst: gst, hst: hst, total: total)
    session[:s_order] = new_order.id
    redirect_back(fallback_location: root_path)
    # redirect_to checkout_create_path, method: :post
  end

  def pre_checkout
    @province = Province.where('name LIKE ?', "%#{params[:province]}%")
    session[:s_province] = @province.first.id
  end

  def add_to_cart
    id = params[:id].to_i
    session[:cart] << id unless session[:cart].include?(id)
    redirect_back(fallback_location: root_path)
    # redirect_to root_path #:back
  end

  def remove_from_cart
    id = params[:id].to_i
    session[:cart].delete(id)
    redirect_back(fallback_location: root_path)
  end

  def select_province
    @province = Province.where('name LIKE ?', "%#{params[:province]}%")
  end

  private

  def initialize_session
    session[:s_province] ||= 0
    session[:cart] ||= []
    session[:s_subtotal] ||= 0
    session[:s_order] ||= 0
    session[:invoice_product] = []
    session[:current_user] ||= 0
  end
end

# <%= form_with(url: pre_checkout_user_path, local:true, method: "post") do |user_form|%>
#   <li>Username<%= user_form.text_field :username %></li>
#   <li>Email: <%= user_form.text_field :email%></li>
#   <li>First name: <%= user_form.text_field :first_name %></li>
#   <li>Last name : <%= user_form.text_field :last_name %></li>
# <%= submit_tag("Save user", class:"button is-info is-small") %>
# <% end %>

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/abouts/index.html.erb
<% @abouts.each do |about| %>
  <h1 class="title is-2"><%=about.title%></h1>
  <h1 class="title is-4"><%=about.history%></h1>
  <h1 class="title is-4"><%=about.description%></h1>

<% end %>

app/views/abouts/show.html.erb
<h1>Abouts#show</h1>
<p>Find me in app/views/abouts/show.html.erb</p>

app/views/orders/index.html.erb
<div class="mainPanel">
  <div class="leftPanel">
    <table class="itemOrder">
    <tr>
      <th>Product</th>
      <th>Qty order</th>
      <th>Stock available</th>
      <th>Price</th>
      <th></th>
    </tr>
      <%subtotal = 0%>
      <% @cart.each do |product|%>
        <tr>
          <td><%=product.title%></td>
          <td class="qty_order">
            <%=@qty_order = text_field_tag product.id, '1', type: 'number'%>
          </td>
          <td class="stock"><%=product.quantity%></td>
          <td><%=number_to_currency product.price.to_i%></td>
          <td><%= link_to 'remove', remove_from_cart_path(product), method: :delete%></td>
        </tr>
      <%subtotal = subtotal + product.price.to_i%>
      <% end %>
    <%session[:s_subtotal] = subtotal%>
    </table>
  </div>
  <div class="rightPanel">
    <div class="rpHeader">
      <h1>Order Summary</h1>
    </div>
    <div class="rpBody">
      <h2>Subtotal: <%=number_to_currency subtotal%></h2>
    </div>
    <div class="rpFooter">
      <%= form_with(url: select_province_path, local:true, method: "get") do %>
        <div class="select is-small" id="selectProvince">
          <% provinces = Province.all%>
          <%=select_tag :province, options_from_collection_for_select(provinces, "name", "name"),prompt: "Select the Province"%>
        </div>
        <div>
          <%= submit_tag("Calculate taxes", class:"button is-info is-small") %>
        </div>
      <% end %>
      <div>
        <%if @province == nil%>
          <p>Please select a province</p>
        <%else%>
          <p>Province: <%=sprovince = @province.first.name%></p>
          <p>PST (<%=@province.first.pst / 1.0%>%):  <%=pst_calc = number_to_currency subtotal*@province.first.pst / 100%></p>
          <p>GST (<%=@province.first.gst / 1.0%>%):  <%=gst_calc = number_to_currency subtotal*@province.first.gst / 100%></p>
          <p>HST (<%=@province.first.hst / 1.0%>%):  <%=hst_calc = number_to_currency subtotal*@province.first.hst / 100%></p>
          <h2>Total: <%=total = number_to_currency subtotal + (subtotal*@province.first.pst + subtotal*@province.first.gst + subtotal*@province.first.hst) / 100%> </h2>
        <%end%>
      </div>
      <p><%=link_to 'Proceed to Checkout', pre_checkout_path(province:sprovince)%></p>
  </div>
</div>
</div>

app/views/orders/pre_checkout.html.erb
<div class="mainPanel">
  <div id="form_user">
    <%= form_with(url: pre_checkout_user_path, local:true, method: "post") do |user_form|%>
    <ul>
      <% if session[:current_user] != 0 %>
        <%current_user = User.find(session[:current_user])%>
        <%current_address = current_user.addresses%>
        <li>Email:<%= user_form.text_field :email, :required => true, :pattern => '[^@]+@[^@]+\.[a-zA-Z]{2,6}', :value=> current_user.email %></li>
        <li>First name:<%= user_form.text_field :first_name, :required => true, :value=> current_user.first_name %></li>
        <li>Last name:<%= user_form.text_field :last_name, :required => true, :value=> current_user.last_name %></li>
        <li>Street:<%= user_form.text_field :street, :required => true, :value=> current_address.first.street %></li>
        <li>City:<%= user_form.text_field :city, :required => true, :value=> current_address.first.city %></li>
        <li>Postal Code:<%= user_form.text_field :postal_code, :required => true, :pattern =>'^[a-zA-Z]{1}[0-9]{1}[a-zA-Z]{1}[- ]{0,1}[0-9]{1}[a-zA-Z]{1}[0-9]{1}', :value=> current_address.first.postal_code  %></li>
      <% else %>
        <li>Email:<%= user_form.text_field :email, :required => true, :pattern => '[^@]+@[^@]+\.[a-zA-Z]{2,6}' %></li>
        <li>First name:<%= user_form.text_field :first_name, :required => true%></li>
        <li>Last name:<%= user_form.text_field :last_name, :required => true %></li>
        <li>Street:<%= user_form.text_field :street, :required => true %></li>
        <li>City:<%= user_form.text_field :city, :required => true %></li>
        <li>Postal Code:<%= user_form.text_field :postal_code, :required => true, :pattern =>'^[a-zA-Z]{1}[0-9]{1}[a-zA-Z]{1}[- ]{0,1}[0-9]{1}[a-zA-Z]{1}[0-9]{1}' %></li>
      <% end %>
      <li>Province: <%= @province.first.name %></li>
    </ul>
    <%= submit_tag("Save your info", class: session[:current_user] != 0 ? "btn-hide-class" : "button is-info is-small") %>
    <%= submit_tag("Change your info", class: session[:current_user] == 0 ? "btn-hide-class" : "button is-info is-small") %>
    <% end %>
    <%=button_to 'Pay now', checkout_create_path, method: :post, class: session[:current_user] == 0 ? "btn-hide-class" : "button is-info is-small",
remote: true%>
  </div>

  <div class="middlePanel">
  <table class="itemOrder">
  <tr>
    <th>Product</th>
    <th>Qty</th>
    <th>Price</th>
  </tr>
    <% @cart.each do |product|%>
      <tr>
        <td><%=product.title%></td>
        <td>1</td>
        <td><%=number_to_currency product.price.to_i%></td>
      </tr>
    <% end %>
  </table>
  </div>

  <div class="rightPanel">
    <h1>Order Summary</h1>
    <% subtotal = session[:s_subtotal]%>
    <h2>Subtotal: <%= number_to_currency subtotal%></h2>
    <p>PST (<%=@province.first.pst / 1.0%>%):  <%=pst_calc = number_to_currency subtotal*@province.first.pst / 100%></p>
    <p>GST (<%=@province.first.gst / 1.0%>%):  <%=gst_calc = number_to_currency subtotal*@province.first.gst / 100%></p>
    <p>HST (<%=@province.first.hst / 1.0%>%):  <%=hst_calc = number_to_currency subtotal*@province.first.hst / 100%></p>
    <h1>Total: <%=total = number_to_currency subtotal + (subtotal*@province.first.pst + subtotal*@province.first.gst + subtotal*@province.first.hst) / 100%> </h1>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<% @users.each do |user| %>
  <p><%= link_to user.username, user %></p>
<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<%=@user.first_name%>