config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'orders/index'
  # get 'contacts/index'
  # get 'abouts/index'
  # get 'abouts/show'
  # get 'products/index'
  # get 'products/show'
  # get 'users/index'
  # get 'users/show'
  get '/users', to: 'users#index'
  get '/users/:id', to: 'users#show', id: /\d+/, as: 'user'
  get '/categories', to: 'categories#index'
  get '/categories/:id', to: 'categories#show', id: /\d+/, as: 'category'
  get '/products', to: 'products#index'
  get '/products/:id', to: 'products#show', id: /\d+/, as: 'product'
  get '/about', to: 'abouts#index'
  get '/contact', to: 'contacts#index'
  get '/searchproduct', to: 'products#search', as: 'searchproduct'
  get '/newproducts', to: 'products#new_products', as: 'newproducts'
  get '/updateproducts', to: 'products#update_products', as: 'updateproducts'
  get '/searchbycategories/:id/', to: 'category#search_by_categories', id: /\d+/, as: 'searchbycategories'

  get '/orders', to: 'orders#index'
  post '/orders/add_to_cart/:id', to: 'orders#add_to_cart', as: 'add_to_cart'
  delete '/orders/remove_from_cart/:id', to: 'orders#remove_from_cart', as: 'remove_from_cart'
  get '/orders', to: 'orders#select_province', as: 'select_province'
  get '/orders/pre_checkout', to: 'orders#pre_checkout', as: 'pre_checkout'
  post '/orders/pre_checkout', to: 'orders#pre_checkout_user', as: 'pre_checkout_user'
  post '/orders/pre_checkout', to: 'orders#pre_checkout_address', as: 'pre_checkout_address'

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success' # 20:54 time youtube video
  end

  root to: 'products#index'
  # get 'categories/index'
  # get 'categories/show'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
end

app/models/address.rb
# frozen_string_literal: true

class Address < ApplicationRecord
  belongs_to :user
  belongs_to :province

  validates :street, :city, :postal_code, presence: true
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :products

  validates :name, presence: true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  belongs_to :user
  has_many :order_products

  validates :status, :pst, :gst, :hst, :total, presence: true
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  belongs_to :user
  belongs_to :category

  has_one_attached :image
  has_many :order_products

  validates :title, :price, :quantity, :description, :image, presence: true
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :addresses
  validates :name, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :products
  has_many :addresses

  validates :username, :email, :first_name, :last_name, presence: true
end

app/controllers/abouts_controller.rb
# frozen_string_literal: true

class AboutsController < ApplicationController
  def index
    @abouts = About.all
  end

  def show; end
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  before_action :initialize_session
  before_action :select_province

  def index
    # @province = Province.all
  end

  def pre_checkout_user
    @province = Province.find(session[:s_province])
    new_user ||= User.create(username: params[:email], email: params[:email], first_name: params[:first_name], last_name: params[:last_name])
    new_user.addresses.create(user_id: new_user.id, province_id: @province.id, street: params[:street], city: params[:city], postal_code: params[:postal_code])
    session[:current_user] = new_user.id
    subtotal = session[:s_subtotal]
    pst = @province.pst.to_f / 100 * subtotal.to_f
    gst = @province.gst.to_f / 100 * subtotal.to_f
    hst = @province.hst.to_f / 100 * subtotal.to_f
    total = subtotal + pst + gst + hst
    new_order = Order.create(user_id: new_user.id, status: 'new', pst: pst, gst: gst, hst: hst, total: total)
    session[:s_order] = new_order.id
    redirect_back(fallback_location: root_path)
    # redirect_to checkout_create_path, method: :post
  end

  def pre_checkout
    @province = Province.where('name LIKE ?', "%#{params[:province]}%")
    session[:s_province] = @province.first.id
  end

  def add_to_cart
    id = params[:id].to_i
    session[:cart] << id unless session[:cart].include?(id)
    redirect_back(fallback_location: root_path)
    # redirect_to root_path #:back
  end

  def remove_from_cart
    id = params[:id].to_i
    session[:cart].delete(id)
    redirect_back(fallback_location: root_path)
  end

  def select_province
    @province = Province.where('name LIKE ?', "%#{params[:province]}%")
  end

  private

  def initialize_session
    session[:s_province] ||= 0
    session[:cart] ||= []
    session[:s_subtotal] ||= 0
    session[:s_order] ||= 0
    session[:invoice_product] = []
    session[:current_user] ||= 0
  end
end

# <%= form_with(url: pre_checkout_user_path, local:true, method: "post") do |user_form|%>
#   <li>Username<%= user_form.text_field :username %></li>
#   <li>Email: <%= user_form.text_field :email%></li>
#   <li>First name: <%= user_form.text_field :first_name %></li>
#   <li>Last name : <%= user_form.text_field :last_name %></li>
# <%= submit_tag("Save user", class:"button is-info is-small") %>
# <% end %>

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  def index
    @products = Product.order(:title).page(params[:page]).per(12)
  end

  def show
    @product = Product.find(params[:id])
  end

  def search
    @products = Product.where('title LIKE ? AND category_id LIKE ?', "%#{params[:search_term]}%", "%#{params[:categories]}%").order(:title).page(params[:page]).per(12)
  end

  def new_products
    @products = Product.where("created_at > date('now','-3 day')").order(:title).page(params[:page]).per(12)
  end

  def update_products
    @products = Product.where("updated_at > date('now','-3 day')").order(:title).page(params[:page]).per(12)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/_product.html.erb
<div class="columns is-multiline">
<% @products.each do |product| %>
  <div class="column is-one-quarter">
    <div class="card">
      <header class="card-header">
        <p class="card-header-title"><%= link_to product.title, product %></p>
      </header>
      <div class="card-image">
        <figure class="image is-4by3">
        <%=link_to image_tag(product.image, size: "100", alt: product.title), product%>
        </figure>
      </div>
      <div class="card-content">
        <div class="media">
          <div class="media-content">
            <p> Price: <%=number_to_currency product.price.to_i%></p>
            <% if @cart%>
              <% if @cart.include?(product) %>
                <p><i>Product added to your cart.</i></p>
                <%= button_to 'Remove from cart', remove_from_cart_path(product), method: :delete%>
              <% else %>
                <p><%=link_to 'add to cart', add_to_cart_path(product.id), method: :post%></p>
              <% end %>
            <% else %>
                <p><%=link_to 'add to cart', add_to_cart_path(product.id), method: :post%></p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<%end%>
</div>

app/views/products/_search_form.html.erb
<div class="searchProduct">
  <%= form_with(url: searchproduct_path, local:true, method: "get") do %>
  <div class="select" id="selectCategory">
    <% categories = Category.group(:name)%>
    <%=select_tag :categories, options_from_collection_for_select(categories, "id", "name"),prompt: "Select a category"%>
  </div>
  <div class="field has-addons" id="searchProductInput">
    <div class="control">
      <%= text_field_tag(:search_term, nil, class:'input', placeholder:'Product by name') %>
    </div>
    <div class="control">
      <%= submit_tag("Search", class:"button is-info") %>
    </div>
  </div>
<% end %>
  <div class="paginate">
    <%=paginate @products%>
  </div>
</div>

app/views/products/index.html.erb
<%=render partial: 'products/search_form'%>

<%=render partial: 'products/product'%>
<%=paginate @products%>

app/views/products/new_products.html.erb
<%=render partial: 'products/search_form'%>
<%=render partial: 'products/product'%>

app/views/products/search.html.erb
<%=render partial: 'products/search_form'%>
<br>
<p class="subtitle is-7">
Found <%=pluralize(@products.size, 'result')%>
for the search term "<%=params[:search_term] %>".
</p>
<%=render partial: 'products/product'%>

app/views/products/show.html.erb
<div class="columns">
  <div class="card1">
    <div class="card-content">
      <div class="media">
        <div class="media-left">
          <figure>
            <%=image_tag(@product.image, size: "400", alt: @product.title)%>
          </figure>
        </div>
        <div class="media-content">
          <p class="title is-4 has-text-danger"><%=@product.title%></p>
          <p> Qty: <%=@product.quantity%></p>
          <p> Price: <%=number_to_currency @product.price.to_i%></p>
          <p>Description: <%=@product.description%></p>
        </div>
      </div>
    </div>
  </div>
</div>


  <footer class="card-footer">
    <p class="tag is-warning is-medium"><%= link_to @product.category.name, @product.category%></p>
  </footer>

app/views/products/update_products.html.erb
<%=render partial: 'products/search_form'%>
<%=render partial: 'products/product'%>