config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'orders/index'
  # get 'contacts/index'
  # get 'abouts/index'
  # get 'abouts/show'
  # get 'products/index'
  # get 'products/show'
  # get 'users/index'
  # get 'users/show'
  get '/users', to: 'users#index'
  get '/users/:id', to: 'users#show', id: /\d+/, as: 'user'
  get '/categories', to: 'categories#index'
  get '/categories/:id', to: 'categories#show', id: /\d+/, as: 'category'
  get '/products', to: 'products#index'
  get '/products/:id', to: 'products#show', id: /\d+/, as: 'product'
  get '/about', to: 'abouts#index'
  get '/contact', to: 'contacts#index'
  get '/searchproduct', to: 'products#search', as: 'searchproduct'
  get '/newproducts', to: 'products#new_products', as: 'newproducts'
  get '/updateproducts', to: 'products#update_products', as: 'updateproducts'
  get '/searchbycategories/:id/', to: 'category#search_by_categories', id: /\d+/, as: 'searchbycategories'

  get '/orders', to: 'orders#index'
  post '/orders/add_to_cart/:id', to: 'orders#add_to_cart', as: 'add_to_cart'
  delete '/orders/remove_from_cart/:id', to: 'orders#remove_from_cart', as: 'remove_from_cart'
  get '/orders', to: 'orders#select_province', as: 'select_province'
  get '/orders/pre_checkout', to: 'orders#pre_checkout', as: 'pre_checkout'
  post '/orders/pre_checkout', to: 'orders#pre_checkout_user', as: 'pre_checkout_user'
  post '/orders/pre_checkout', to: 'orders#pre_checkout_address', as: 'pre_checkout_address'

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success' # 20:54 time youtube video
  end

  root to: 'products#index'
  # get 'categories/index'
  # get 'categories/show'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
end

app/models/address.rb
# frozen_string_literal: true

class Address < ApplicationRecord
  belongs_to :user
  belongs_to :province

  validates :street, :city, :postal_code, presence: true
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :products

  validates :name, presence: true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  belongs_to :user
  has_many :order_products

  validates :status, :pst, :gst, :hst, :total, presence: true
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  belongs_to :user
  belongs_to :category

  has_one_attached :image
  has_many :order_products

  validates :title, :price, :quantity, :description, :image, presence: true
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :addresses
  validates :name, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :products
  has_many :addresses

  validates :username, :email, :first_name, :last_name, presence: true
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Red River Bay</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://js.stripe.com/v3/"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">

  </head>

  <body>
    <section class="section has-text-dark">
    <div class="container">
      <header>
        <div id="topHeader">
          <h1 class="title is-1 is-danger has-danger"><%= link_to image_tag("logo.png", alt: "Red River Bay logo"), root_path %></h1>
          <div id="shoppingCartHeader">
          <% if @cart%>
            <p><%= link_to image_tag("shopping_cart.png" ,size: "30", alt: "Shopping Cart Icon"), orders_path %></p>
            <p>Items: <%=@cart.count%></p>
          <% end %>
          </div>
        </div>
        <h2><%= link_to 'Products', root_path %> | <%= link_to 'Categories', categories_path %> | <b><%= link_to 'New Products', newproducts_path %></b> | <b><%= link_to 'Updated Products', updateproducts_path %></b> | <%= link_to 'About', about_path %> | <%= link_to 'Contact', contact_path %> </h2>
      </header>
    <%= yield %>
    </div>
    </section>
  </body>
</html>